# Base URL used when generating links to your pages
# Set to the URL for your site
baseURL = "https://gwongz.github.io"

# The name of this wonderful theme ;-).
theme = 'hugo-book'

# Basic metadata configuration for your blog.
title = "gwongz's homepage"
author = "Grace Wong"
copyright = "Copyright © 2024, Grace Wong."
languageCode = "en-US"
custom_js = ["js/custom.js"]

[params]
  # (Optional, default docs) Specify section of content to render as menu
  # You can also set value to "*" to render all sections to menu
  BookSection = 'projects'

  BookRepo = 'https://github.com/gwongz/gwongz.github.io'
  BookDateFormat = "January 2, 2006"
  BookComments = false


[module]
  [[module.mounts]]
    source = "assets"
    target = "assets"


